name: Code Review
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  setup-deepseek-review:
    if: github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@eccde2e9781008d795e366b951e313e37af88dd5
        with:
          chat-token: ${{ secrets.CHAT_TOKEN }}
