name: Code Review
on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]
    if: github.event.issue.pull_request


permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  setup-deepseek-review:
    if: github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@eccde2e9781008d795e366b951e313e37af88dd5
        with:
          chat-token: ${{ secrets.CHAT_TOKEN }}
          watch-mention: "@github-actions"
          allowed-associations: "OWNER,MEMBER,COLLABORATOR"
